; Pass 05 allocated long text preview
; Generated by tools/text_repoint_allocator.py
; This assumes Bank BB zero tail is intentionally used as overflow space.
; Overflow region: $BBBDF8-$BC0000 exclusive (16904 bytes)
; Not automatically included. Review, then replace the matching zero tail region or include manually.

ORG $BBBDF8

; index $02D | old B6:B69DF4 | Text_Shop_Closed
; new location $BBBDF8, size 290 bytes
Text_Repoint_02D_Shop_Closed:
                       dw $002D,$0007,$0004,$00B1,$0012,$0007,$000E,$000F
                       dw $00B1,$0008,$0012,$00B1,$0002,$000B,$000E,$0012
                       dw $0004,$0003,$00B1,$0013,$000E,$0003,$0000,$0018
                       dw $0036,$00B1,$0029,$000B,$0004,$0000,$0012,$0004
                       dw $00B1,$0002,$000E,$000C,$0004,$00B1,$0001,$0000
                       dw $0002,$000A,$00B1,$0013,$000E,$000C,$000E,$0011
                       dw $0011,$000E,$0016,$00B1,$000C,$000E,$0011,$000D
                       dw $0008,$000D,$0006,$00B1,$0016,$0007,$0004,$000D
                       dw $00B1,$0016,$0004,$00B1,$000E,$000F,$0004,$000D
                       dw $00B1,$0000,$0006,$0000,$0008,$000D,$0036,$00B1
                       dw $002D,$0007,$0000,$000D,$000A,$00B1,$0018,$000E
                       dw $0014,$00B1,$0005,$000E,$0011,$00B1,$0014,$000D
                       dw $0003,$0004,$0011,$0012,$0013,$0000,$000D,$0003
                       dw $0008,$000D,$0006,$00B1,$0000,$000D,$0003,$00B1
                       dw $0007,$0000,$0015,$0004,$00B1,$0000,$00B1,$000F
                       dw $0004,$0000,$0002,$0004,$0005,$0014,$000B,$00B1
                       dw $0003,$0000,$0018,$00B1,$000E,$000D,$00B1,$0013
                       dw $0007,$0004,$00B1,$0005,$0000,$0011,$000C,$0036
                       dw $FFFF

; index $035 | old B6:B6A03E | Text_035_Dialog_HowsGoingWorkTooHard
; new location $BBBF1A, size 272 bytes
Text_Repoint_035_035_Dialog_HowsGoingWorkTooHard:
                       dw $0021,$000E,$0016,$00B1,$0008,$0012,$00B1,$0013
                       dw $0007,$0004,$00B1,$0005,$0000,$0011,$000C,$00B1
                       dw $0006,$000E,$0008,$000D,$0006,$0037,$00B1,$002B
                       dw $0004,$000C,$0004,$000C,$0001,$0004,$0011,$00B1
                       dw $0013,$000E,$00B1,$0011,$0004,$0012,$0013,$00B1
                       dw $0016,$0007,$0004,$000D,$00B1,$0018,$000E,$0014
                       dw $00B1,$0000,$0011,$0004,$00B1,$0013,$0008,$0011
                       dw $0004,$0003,$0036,$00B1,$0030,$000E,$0011,$000A
                       dw $0008,$000D,$0006,$00B1,$0013,$000E,$000E,$00B1
                       dw $0007,$0000,$0011,$0003,$00B1,$0004,$0015,$0004
                       dw $0011,$0018,$00B1,$0012,$0008,$000D,$0006,$000B
                       dw $0004,$00B1,$0003,$0000,$0018,$00B1,$0002,$0000
                       dw $000D,$00B1,$000C,$0000,$000A,$0004,$00B1,$0013
                       dw $000E,$000C,$000E,$0011,$0011,$000E,$0016,$00B1
                       dw $000C,$0014,$0002,$0007,$00B1,$0007,$0000,$0011
                       dw $0003,$0004,$0011,$00B1,$0013,$0007,$0000,$000D
                       dw $00B1,$0013,$000E,$0003,$0000,$0018,$0036,$FFFF

; Remaining overflow bytes after allocated preview: 16342
; Keep the rest as zero bytes if replacing the existing tail.