#!/usr/bin/env python3
"""Allocate too-long text edits into the known Bank BB zero tail.

This emits preview ASM only. It does not modify src/data_banks/bank_BB.asm or
src/code_banks/bank_83.asm. The known tail in the current USA source starts at
$BBBDF8 and extends to $BC0000, giving 16,904 bytes of conservative expansion
space inside the existing 2MB ROM layout.
"""
from __future__ import annotations
import argparse, csv, json, re
from pathlib import Path
from typing import List, Dict

from hm_text_codec import encode_markup_text, format_dw

DEFAULT_START = 0xBBBDF8
DEFAULT_END = 0xBC0000


def safe_label_piece(text: str, limit: int = 42) -> str:
    text = re.sub(r"^Text_", "", text)
    text = re.sub(r"[^A-Za-z0-9]+", "_", text).strip("_")
    return (text[:limit].strip("_") or "EditedText")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", default=".")
    ap.add_argument("--csv", default="examples/pass05_example_text_repoint_edits.csv")
    ap.add_argument("--start", default=f"{DEFAULT_START:06X}", help="SNES address for overflow start, default BBBDF8")
    ap.add_argument("--end", default=f"{DEFAULT_END:06X}", help="exclusive SNES address for overflow end, default BC0000")
    ap.add_argument("--outdir", default="reports/decomp_pass05/text/allocation_example")
    ap.add_argument("--asm-out", default="patches/pass05_allocated_text_blocks_preview.asm")
    ap.add_argument("--pointer-out", default="patches/pass05_allocated_pointer_table_replacements_preview.asm")
    args = ap.parse_args()

    repo = Path(args.repo)
    rows = list(csv.DictReader((repo / args.csv).open(encoding="utf-8")))
    start = int(args.start.replace("$", ""), 16)
    end = int(args.end.replace("$", ""), 16)
    cursor = start
    allocations: List[Dict[str, object]] = []
    asm_lines = [
        "; Pass 05 allocated long text preview",
        "; Generated by tools/text_repoint_allocator.py",
        "; This assumes Bank BB zero tail is intentionally used as overflow space.",
        f"; Overflow region: ${start:06X}-${end:06X} exclusive ({end-start} bytes)",
        "; Not automatically included. Review, then replace the matching zero tail region or include manually.",
        "",
        f"ORG ${start:06X}",
        "",
    ]
    ptr_lines = [
        "; Pass 05 allocated pointer-table replacements",
        "; Replace matching lines inside Text_Pointer_Table in src/code_banks/bank_83.asm after inserting blocks.",
        "",
    ]

    for row in rows:
        edited = (row.get("edited_text") or "").strip("\ufeff")
        original = row.get("markup_text") or ""
        if not edited or edited == original:
            continue
        try:
            encoded = encode_markup_text(edited)
        except Exception as exc:  # noqa: BLE001
            allocations.append({
                "index_hex": row.get("index_hex", ""), "label": row.get("label", ""),
                "status": f"ENCODE_ERROR: {exc}",
            })
            continue
        old_words = int(row.get("max_words") or 0)
        if len(encoded) <= old_words:
            continue
        size = len(encoded) * 2
        label = f"Text_Repoint_{row.get('index_hex','XXX')}_{safe_label_piece(row.get('label','Text_Unknown'))}"
        addr = cursor
        new_end = cursor + size
        status = "ALLOCATED" if new_end <= end else "NO_SPACE"
        allocations.append({
            "index_hex": row.get("index_hex", ""),
            "old_bank": row.get("bank", ""),
            "old_snes_addr": row.get("snes_addr", ""),
            "old_label": row.get("label", ""),
            "new_label": label,
            "new_snes_addr": f"{addr:06X}",
            "new_end_exclusive": f"{new_end:06X}",
            "old_words": old_words,
            "new_words": len(encoded),
            "delta_words": len(encoded) - old_words,
            "bytes": size,
            "status": status,
        })
        if status == "ALLOCATED":
            asm_lines.append(f"; index ${row.get('index_hex')} | old {row.get('bank')}:{row.get('snes_addr')} | {row.get('label')}")
            asm_lines.append(f"; new location ${addr:06X}, size {size} bytes")
            asm_lines.append(f"{label}:")
            asm_lines.append(format_dw(encoded))
            asm_lines.append("")
            ptr_lines.append(f"; index ${row.get('index_hex')} | old {row.get('label')}")
            ptr_lines.append(f"        dl {label:<50} ; ${addr:06X}")
            ptr_lines.append("")
            cursor = new_end

    remaining = end - cursor
    if remaining > 0:
        asm_lines += [
            f"; Remaining overflow bytes after allocated preview: {remaining}",
            "; Keep the rest as zero bytes if replacing the existing tail.",
        ]

    outdir = repo / args.outdir
    outdir.mkdir(parents=True, exist_ok=True)
    csv_path = outdir / "text_repoint_allocation.csv"
    if allocations:
        fieldnames = sorted({k for row in allocations for k in row.keys()})
        with csv_path.open("w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=fieldnames)
            w.writeheader(); w.writerows(allocations)
    else:
        csv_path.write_text("status\nNO_REPOINTS\n", encoding="utf-8")
    (outdir / "text_repoint_allocation.json").write_text(json.dumps(allocations, indent=2, ensure_ascii=False), encoding="utf-8")
    (repo / args.asm_out).write_text("\n".join(asm_lines), encoding="utf-8")
    (repo / args.pointer_out).write_text("\n".join(ptr_lines), encoding="utf-8")

    allocated = [a for a in allocations if a.get("status") == "ALLOCATED"]
    no_space = [a for a in allocations if a.get("status") == "NO_SPACE"]
    used = cursor - start
    md = [
        "# Pass 05 - allocated text repoint preview", "",
        f"Input CSV: `{args.csv}`", "",
        f"- Overflow start: `${start:06X}`",
        f"- Overflow end exclusive: `${end:06X}`",
        f"- Total overflow bytes: **{end-start}**",
        f"- Allocated entries: **{len(allocated)}**",
        f"- Used bytes: **{used}**",
        f"- Remaining bytes: **{max(0, remaining)}**",
        f"- No-space entries: **{len(no_space)}**",
        "",
        "## Files", "",
        f"- `{args.asm_out}`",
        f"- `{args.pointer_out}`",
        f"- `{csv_path.relative_to(repo)}`",
        "",
        "## Allocation table", "",
        "| index | old label | new label | addr | bytes | status |",
        "|---:|---|---|---:|---:|---|",
    ]
    for a in allocations:
        md.append(f"| ${a.get('index_hex','')} | `{a.get('old_label','')}` | `{a.get('new_label','')}` | `{a.get('new_snes_addr','')}` | {a.get('bytes','')} | {a.get('status','')} |")
    if not allocations:
        md.append("| - | - | - | - | - | NO_REPOINTS |")
    md += ["", "This is a preview. Apply it only after reviewing Bank BB tail usage and then rebuild/test in emulator."]
    (outdir / "text_repoint_allocation.md").write_text("\n".join(md), encoding="utf-8")
    print(f"Allocated={len(allocated)} used={used} remaining={max(0, remaining)} no_space={len(no_space)}")
    return 1 if no_space else 0

if __name__ == "__main__":
    raise SystemExit(main())
